---
- name: Ensure portainer-agent directory
  ansible.builtin.file:
    path: "{{ portainer_data_dir }}/portainer-agent"
    state: directory
    owner: root
    group: root
    mode: "0755"
  become: true
  become_user: root

- name: Deploy portainer-agent docker compose file
  ansible.builtin.template:
    src: portainer-agent.j2
    dest: "{{ portainer_data_dir }}/portainer-agent/compose.yml"
    owner: root
    group: root
    mode: '0644'
  become: true
  become_user: root

- name: Tear down existing services
  community.docker.docker_compose_v2:
    project_src: "{{ portainer_data_dir }}/portainer-agent"
    state: absent
  become: true
  become_user: root

- name: Create and start service
  community.docker.docker_compose_v2:
    project_src: "{{ portainer_data_dir }}/portainer-agent"
  become: true
  become_user: root
